### ISSUE TITLE
Crash when opening 1.1 world

### ISSUE THREAD

**Issue by Creeperface01** [protolambda/blocktopograph#2]
blocktopograph crashes when opening world from mcpe 1.1

**Comment by inxomnyaa** [comment]
The reason for this is that the world format somehow changed once again,

> Matt ... [9:04 AM] 
I can also get maps to render by treating the 1.1 format the same as the 0.9 format; I'm not sure if there are any differences between the two formats yet, but the rest works just fine.

**Comment by jocopa3** [comment]
@thebigsmileXD It's not quite that the chunk format itself has changed (that was my mistake), but that the version number changed. The reason Blocktopograph crashes is because [of this line](https://github.com/protolambda/blocktopograph/blob/master/app/src/main/java/com/protolambda/blocktopograph/chunk/Chunk.java#L34) in Chunk.getTerrain:

```data = this.getVersion().createTerrainChunkData(this, subChunk);```

The crash happens because `Chunk.getVersion()` ultimately returns `NULL` as version 4 is an unknown format. Calling `Version.createTerrainChunkData` on the value returned by `getVersion()` consequently returns null, so a `NullPointerExcepion` exception is thrown. However, there are no exception handlers for the resulting `NullPointerException`, so the app crashes.

I fixed this in my desktop port by adding a new version called `UNKNOWN`, and returning `UNKNOWN` rather than `NULL` when encountering a new format version. I also added a new version enum for version 4, which is basically the [same as the `V1_0` enum](https://github.com/protolambda/blocktopograph/blob/master/app/src/main/java/com/protolambda/blocktopograph/chunk/Version.java#L16) but with the version Id incremented.

**Comment by jose-vm** [comment]
@jocopa3 Are you able to fix the android version, tho?

**Comment by inxomnyaa** [comment]
@josevazqm its basically the same, the pc version is based on the android one
Also i think he already is, according to the thirdparty devs chat

**Comment by jocopa3** [comment]
@josevazqm It's up to @protolambda to fix the Android app, as he is the owner of it and is the only one who can upload a fix to the Play store.

**Comment by protolambda** [comment]
I currently don't have much time to spend on Blocktopograph, but I'll try to push a fix next week.

**Comment by protolambda** [comment]
Just published an experimental update for MCPE 1.1.0. This should fix it, feel free to re-open if there is still something wrong. (FYI: Blocklight is not supported anymore, and nether support is downgraded. Blame optimizations in MCPE).

**Comment by inxomnyaa** [comment]
+ProOptimizations :D
